Byttet ut feeder med kafka
navikt/veilarbaktivitet pull request #143
Opened 2021-04-07 08:50 UTC by AlexGaard

2021-04-07 09:08 UTC, hakonph commented on src/main/java/no/nav/veilarbaktivitet/config/HelsesjekkConfig.java
> -                new SelfTestCheck("KafkaHelsesjekk", false, kafkaHelsesjekk),
Neon grunn til at du fjernet kafka helsesjekken?

2021-04-07 09:21 UTC, AlexGaard commented on src/main/java/no/nav/veilarbaktivitet/config/HelsesjekkConfig.java
> -                new SelfTestCheck("KafkaHelsesjekk", false, kafkaHelsesjekk),
Tror jeg hadde planer om å introdusere en felles helsesjekk eller no i fellesbiblioteket, men det har ikke blitt noe av det enda, så det er nok best å legge den tilbake inntil videre.

2021-04-07 09:28 UTC, hakonph requested changes

2021-04-07 09:28 UTC, hakonph commented on src/main/java/no/nav/veilarbaktivitet/domain/kafka/EndringsType.java
> +package no.nav.veilarbaktivitet.domain.kafka;
ville ikke flyttet denne

2021-04-07 09:28 UTC, hakonph commented on src/main/java/no/nav/veilarbaktivitet/domain/kafka/KafkaAktivitetMeldingV4.java
> +package no.nav.veilarbaktivitet.domain.kafka;
ville ikke flyttet denne

2021-04-07 09:28 UTC, hakonph commented on src/main/java/no/nav/veilarbaktivitet/domain/kafka/KvpAvsluttetKafkaDTO.java
> +package no.nav.veilarbaktivitet.domain.kafka;
denne hører til i kvp mappen

2021-04-07 09:28 UTC, hakonph commented on src/main/java/no/nav/veilarbaktivitet/service/AktiviteterTilKafkaService.java
> +package no.nav.veilarbaktivitet.service;
ville ikke flyttet denne

2021-04-09 08:23 UTC, hakonph approved these changes

2021-04-09 08:23 UTC, merged