Endrer datamodell for lagring av fho
navikt/veilarbaktivitet pull request #172
Opened 2021-05-27 09:38 UTC by izisfro

* Flytter FHO ut til en egen tabell, med referanse til AKTIVITET tabell på versjon og id
* Aktivitet får ny oppføring når man lagrer og leser fho med de gamle transaksjonstypene
* Endepunkt returnerer fortsatt hele aktivitet objektet med minimal fho data, det er mer data tilgjengelig som jeg ikke vet om skal sendes og som evt skal sendes forskjellig for veileder og bruker
* Jeg har bevist utelatt script som sletter AKTIVITET kolonnene for å gjøre det lettere å deploye og rulle tilbake fram til det er testet litt

2021-05-27 10:04 UTC, theahj approved these changes

2021-05-27 10:04 UTC, theahj commented on src/main/resources/db/migration/V1_42__tabell_forhaandsorientering.sql
> +
Burde vi også lage en index her? Ser vi gjorde det på lest når vi la til den 🤔

2021-05-27 11:33 UTC, izisfro commented
trenger vi VARSEL_ID, SKAL_STOPPES i forhåndsorientring tabellen?

2021-05-27 11:46 UTC, magnusevnav commented
> trenger vi VARSEL_ID, SKAL_STOPPES i forhåndsorientring tabellen?

Ja, vi trenger en VarselId og et "er sendt done melding" flagg, feks en VarselStoppet timestamp som er nullable

2021-05-27 11:57 UTC, izisfro commented on src/main/resources/db/migration/V1_42__tabell_forhaandsorientering.sql
> +
Ja, det kan hende:) Hvordan burde indexen være?

2021-05-27 12:04 UTC, izisfro commented on src/main/resources/db/migration/V1_42__tabell_forhaandsorientering.sql
> +
sånn? `create index aktivitet_fho_lest_idx on AKTIVITET (AKTIVITET_ID, VERSJON, GJELDENDE, fho_id);`

2021-05-28 11:18 UTC, theahj commented on src/main/resources/db/migration/V1_42__tabell_forhaandsorientering.sql
> +
Det var i hvert fall det vi hadde på den forrige. Egentlig @hakonph som har litt bedre kontroll på indeksering

2021-05-28 13:17 UTC, holymaloney requested changes
Sjekk om vi trenger å ta hensyn til eventuelle flere versjoner av fho for en aktivitet. De andre kommentarene kan du vurdere om du ønsker å gjøre noe med eller ikke.

2021-05-30 09:07 UTC, izisfro commented on src/main/java/no/nav/veilarbaktivitet/avtaltMedNav/AvtaltMedNavController.java
> +        Forhaandsorientering fho = avtaltMedNavService.hentForhaandsorientering(lestDTO.aktivitetId);
Nei, bare en per aktivitet

2021-05-30 09:47 UTC, izisfro commented on src/main/resources/db/migration/V1_43__tabell_forhaandsorientering.sql
> +    AKTIVITET_VERSJON NVARCHAR2(255),
Nå ble jeg usikker på hvorfor det ble en varchar, har nok bare surra, ser at de andre tabellene med versjon bruker number så da bytter jeg til det

2021-05-31 06:53 UTC, holymaloney approved these changes

2021-05-31 06:53 UTC, merged