[FO-2505] mote sms
navikt/veilarbaktivitet pull request #53
Opened 2020-08-31 06:43 UTC by hakonph

2020-08-31 13:59 UTC, izisfro requested changes
Savner noen db constraints, har kommet med forslag i kommentarene

2020-08-31 13:59 UTC, izisfro commented on src/main/resources/db/migration/V1_30__mote_pamindelse_varsel.sql
> +    AKTIVITET_ID Number(19)   not null,
Foreign key til aktivitet, primary key?

2020-08-31 13:59 UTC, izisfro commented on src/main/resources/db/migration/V1_30__mote_pamindelse_varsel.sql
> +    AKTIVITET_ID      Number(19)     not null,
Foreign key?

2020-08-31 13:59 UTC, izisfro commented on src/main/resources/db/migration/V1_30__mote_pamindelse_varsel.sql
> +    VARSEL_ID         nvarchar2(255) not null,
primary key?

2020-08-31 13:59 UTC, izisfro commented on src/main/resources/db/migration/V1_30__mote_pamindelse_varsel.sql
> +    VARSEL_ID         nvarchar2(255) not null,
evt er AKTIVITET_ID+AKTIVITET_VERSJON pk?

2020-08-31 13:59 UTC, izisfro commented on src/test/java/no/nav/veilarbaktivitet/db/dao/MoteSMSDAOTest.java
> +    public void tet() {
Que?

2020-08-31 13:59 UTC, izisfro commented on src/test/java/no/nav/veilarbaktivitet/db/dao/MoteSMSDAOTest.java
> +        List<SmsAktivitetData> smsAktivitetData = moteSmsDAO.hentMoterMellom(earlyCuttoff, lateCuttof);
Hadde det ikke vært mer interessant å teste om fratidspunkt på hentMoterMellom er likt som datoen på møte som skal hentes. Altså om du får møter "fra og med" og "til og med" eller ikke

2020-08-31 13:59 UTC, izisfro commented on src/test/java/no/nav/veilarbaktivitet/db/dao/MoteSMSDAOTest.java
> +        //assertThat(smsAktivitetData.size()).isEqualTo(0); //tilsynelatende andledes tolkgning mellom h2 og oracle
Her mangler det assertions

2020-08-31 13:59 UTC, izisfro commented on src/test/java/no/nav/veilarbaktivitet/db/dao/MoteSMSDAOTest.java
> +        //assertThat(smsAktivitetData.size()).isEqualTo(0); //tilsynelatende andledes tolkgning mellom h2 og oracle
Left joinen henter vel alle møtene som er mellom tidspunktene selv om det ikke er treff i GJELDENDE_MOTE_SMS

2020-09-01 07:52 UTC, alexander-svendsen requested changes
Savner metrikker for dette også. Tenker det kan fornuftig å ha i starten for å verifisere at det funker

2020-09-01 07:52 UTC, alexander-svendsen commented on src/main/java/no/nav/veilarbaktivitet/db/dao/MoteSmsDAO.java
> +    public void insertSmsSendt(long aktiviteteId, long aktivtetVerson, Date motetTid, String varselId) {
Race condition her. Kjøres dette bare på leaderen ?

2020-09-01 07:52 UTC, alexander-svendsen commented on src/main/java/no/nav/veilarbaktivitet/helsesjekk/VarselQueHelsesjekk.java
> +            varselQueue.getConnectionFactory().createConnection().close();
Går greit å åpne og lukke connections såpass ofte som helsesjekken blir kalt ?

2020-09-01 07:52 UTC, alexander-svendsen commented on src/main/java/no/nav/veilarbaktivitet/util/IsLeader.java
> +public class IsLeader {
Denne finnes i prosjektet, så tenker du ikke trenger denne klassen

```
    @Bean
    public LeaderElectionClient leaderElectionClient() {
        return new LeaderElectionHttpClient();
    }
```

2020-09-01 12:07 UTC, hakonph commented on src/main/java/no/nav/veilarbaktivitet/db/dao/MoteSmsDAO.java
> +    public void insertSmsSendt(long aktiviteteId, long aktivtetVerson, Date motetTid, String varselId) {
kjøres bare på leader

2020-09-01 12:38 UTC, hakonph commented on src/test/java/no/nav/veilarbaktivitet/db/dao/MoteSMSDAOTest.java
> +        List<SmsAktivitetData> smsAktivitetData = moteSmsDAO.hentMoterMellom(earlyCuttoff, lateCuttof);
tenker det ikke er så viktig om den er fra og med eller fra, da den kjøres hoppas ofte.
men er smartere og ta de samme dag

2020-09-02 08:27 UTC, izisfro commented on src/main/resources/db/migration/V1_30__mote_pamindelse_varsel.sql
> +        CONSTRAINT MOTE_SMS_HISTORIKK_AKTIVITET_FK  FOREIGN KEY (AKTIVITET_ID, VERSJON) REFERENCES AKTIVITET
Hadde det ikke holdt me at AKTIVITET_ID er foreign key til AKTIVITET(AKTIVITET_ID)? Skal vel helst referere til en pk?

2020-09-02 08:35 UTC, izisfro approved these changes
Ser bra ut men kan du squashe?

2020-09-02 12:21 UTC, alexander-svendsen commented on src/main/java/no/nav/veilarbaktivitet/service/MoteSMSService.java
> +        registry.counter("moteSMSHendtet").increment(aktiviteter.count());
moteSMSHendtet???

2020-09-02 12:26 UTC, alexander-svendsen approved these changes

2020-09-02 13:16 UTC, merged